In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import math as math
%matplotlib inline

In [2]:
file = pd.read_csv('fifa21_train.csv')
fileVal = pd.read_csv('fifa21_validate.csv')

In [3]:
#First of all I'm going to eliminate the columns I think are unrelevant
file = file.drop(['Name', 'Nationality', 'Club', 'Team & Contract', 'Joined', 'Loan Date End', 'Contract', 'Position'], axis=1)
fileVal = fileVal.drop(['Name', 'Nationality', 'Club', 'Team & Contract', 'Joined', 'Loan Date End', 'Contract', 'Position'], axis=1)

In [4]:
#Then I'm going to find the correlations among the columns that are the sum of others and
#I'll eliminate those with corr>85%

In [5]:
file_test = file[['Attacking', 'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys']]
correlations_matrix = file_test.corr()
correlations_matrix

,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys
Attacking,1.000000,0.842204,0.877748,0.705065,0.880607,0.898636
Crossing,0.842204,1.000000,0.645621,0.435570,0.800162,0.676382
Finishing,0.877748,0.645621,1.000000,0.455388,0.650934,0.891072
Heading Accuracy,0.705065,0.435570,0.455388,1.000000,0.630159,0.490921
Short Passing,0.880607,0.800162,0.650934,0.630159,1.000000,0.685027
Volleys,0.898636,0.676382,0.891072,0.490921,0.685027,1.000000

In [6]:
file_test = file[['Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control']]
correlations_matrix = file_test.corr()
correlations_matrix

,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control
Skill,1.000000,0.933298,0.934255,0.890196,0.839226,0.940600
Dribbling,0.933298,1.000000,0.844690,0.744447,0.704079,0.938222
Curve,0.934255,0.844690,1.000000,0.855255,0.694941,0.826975
FK Accuracy,0.890196,0.744447,0.855255,1.000000,0.689447,0.746248
Long Passing,0.839226,0.704079,0.694941,0.689447,1.000000,0.773170
Ball Control,0.940600,0.938222,0.826975,0.746248,0.773170,1.000000

In [7]:
file_test = file[['Movement', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance']]
correlations_matrix = file_test.corr()
correlations_matrix

,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance
Movement,1.000000,0.923445,0.885792,0.925079,0.319950,0.839316
Acceleration,0.923445,1.000000,0.925976,0.823438,0.127487,0.706167
Sprint Speed,0.885792,0.925976,1.000000,0.759953,0.129795,0.623763
Agility,0.925079,0.823438,0.759953,1.000000,0.228676,0.784823
Reactions,0.319950,0.127487,0.129795,0.228676,1.000000,0.125709
Balance,0.839316,0.706167,0.623763,0.784823,0.125709,1.000000

In [8]:
file_test = file[['Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots']]
correlations_matrix = file_test.corr()
correlations_matrix

               Power  Shot Power   Jumping   Stamina  Strength  Long Shots
Power       1.000000    0.765745  0.498094  0.760756  0.478583    0.806966
Shot Power  0.765745    1.000000  0.111710  0.369335  0.178469    0.804333
Jumping     0.498094    0.111710  1.000000  0.329194  0.335127    0.097072
Stamina     0.760756    0.369335  0.329194  1.000000  0.237740    0.550738
Strength    0.478583    0.178469  0.335127  0.237740  1.000000    0.051398
Long Shots  0.806966    0.804333  0.097072  0.550738  0.051398    1.000000

In [9]:
file_test = file[['Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties','Composure']]
correlations_matrix = file_test.corr()
correlations_matrix

,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure
Mentality,1.000000,0.771031,0.612562,0.808293,0.730438,0.731226,0.752872
Aggression,0.771031,1.000000,0.726117,0.380099,0.294373,0.323653,0.537952
Interceptions,0.612562,0.726117,1.000000,0.128998,0.157621,0.051953,0.382893
Positioning,0.808293,0.380099,0.128998,1.000000,0.734557,0.804764,0.619551
Vision,0.730438,0.294373,0.157621,0.734557,1.000000,0.631481,0.669555
Penalties,0.731226,0.323653,0.051953,0.804764,0.631481,1.000000,0.590426
Composure,0.752872,0.537952,0.382893,0.619551,0.669555,0.590426,1.000000

In [10]:
file_test = file[['Defending', 'Marking', 'Standing Tackle', 'Sliding Tackle']]
correlations_matrix = file_test.corr()
correlations_matrix

                 Defending   Marking  Standing Tackle  Sliding Tackle
Defending         1.000000  0.965015         0.986358        0.984713
Marking           0.965015  1.000000         0.925376        0.917240
Standing Tackle   0.986358  0.925376         1.000000        0.974528
Sliding Tackle    0.984713  0.917240         0.974528        1.000000

In [11]:
file_test = file[['Goalkeeping', 'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes']]
correlations_matrix = file_test.corr()
correlations_matrix

,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes
Goalkeeping,1.000000,0.987614,0.986244,0.970355,0.986088,0.987827
GK Diving,0.987614,1.000000,0.967233,0.947707,0.966919,0.970911
GK Handling,0.986244,0.967233,1.000000,0.953500,0.967224,0.968606
GK Kicking,0.970355,0.947707,0.953500,1.000000,0.953459,0.954432
GK Positioning,0.986088,0.966919,0.967224,0.953459,1.000000,0.967905
GK Reflexes,0.987827,0.970911,0.968606,0.954432,0.967905,1.000000

In [12]:
#Cleaning all with corr > 0.85
file = file.drop(['Crossing', 'Finishing', 'Short Passing', 'Volleys', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Acceleration', 'Sprint Speed', 'Agility', 'Balance', 'Marking', 'Standing Tackle', 'Sliding Tackle', 'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes'], axis=1)
fileVal = fileVal.drop(['Crossing', 'Finishing', 'Short Passing', 'Volleys', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Acceleration', 'Sprint Speed', 'Agility', 'Balance', 'Marking', 'Standing Tackle', 'Sliding Tackle', 'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes'], axis=1)

In [13]:
file_num = file.select_dtypes('number')

In [14]:
#I'm going to replace the NaN with the mean
for col in file_num:
        mean = int(file_num[col].mean())
        file[col] = file_num[col].fillna(mean)

In [15]:
file_num = fileVal.select_dtypes('number')
for col in file_num:
        mean = int(file_num[col].mean())
        fileVal[col] = file_num[col].fillna(mean)

In [16]:
#Checking again corr from all with all (cleaned all with corr>85%)
file = file.drop(['Total Stats', 'Skill', 'Mentality', 'Long Shots', 'Positioning', 'Defending', 'Interceptions', 'Strength'], axis=1)
fileVal = fileVal.drop(['Total Stats', 'Skill', 'Mentality', 'Long Shots', 'Positioning', 'Defending', 'Interceptions', 'Strength'], axis=1)

In [17]:
file_num = file.select_dtypes('number')

In [18]:
file_cat = file.select_dtypes('object')

In [19]:
#Filling NaN in Cat columns

In [20]:
file['A/W'] = file['A/W'].fillna('Medium')
fileVal['A/W'] = fileVal['A/W'].fillna('Medium')

In [21]:
file['D/W'] = file['D/W'].fillna('Medium')
fileVal['D/W'] = fileVal['D/W'].fillna('Medium')

In [22]:
#I'm going to eliminate the symbols or in those columns which have it
file['W/F'] = file['W/F'].str.rstrip('★').astype('int')
file['SM'] = file['SM'].str.rstrip('★').astype('int')
file['IR'] = file['IR'].str.rstrip('★').astype('int')
file['Weight'] = file['Weight'].str.rstrip('lbs').astype('int')

In [23]:
fileVal['W/F'] = fileVal['W/F'].str.rstrip('★').astype('int')
fileVal['SM'] = fileVal['SM'].str.rstrip('★').astype('int')
fileVal['IR'] = fileVal['IR'].str.rstrip('★').astype('int')
fileVal['Weight'] = fileVal['Weight'].str.rstrip('lbs').astype('int')

In [24]:
#Converting of height to integer
def height (x):
    x=x.replace('"','')
    f,i=x.split("\'")
    x=round(int(f)+int(i)/12,2)
    return x
file['Height']=list(map(height, file['Height']))
fileVal['Height']=list(map(height, fileVal['Height']))

In [25]:
# convertion of amounts (€) to integer
def amount (x):
    x=x.replace('€','')
    if 'K' in x:
        scalar=1000
        x=x.replace('K','')
    elif 'M' in x:
        scalar=1000000
        x=x.replace('M','')
    else:
        scalar=1
    x=pd.to_numeric(x, errors='coerce')*scalar
    return x
file['Value']=list(map(amount, file['Value']))
file['Wage']=list(map(amount, file['Wage']))
file['Release Clause']=list(map(amount, file['Release Clause']))

In [26]:
fileVal['Value']=list(map(amount, fileVal['Value']))
fileVal['Wage']=list(map(amount, fileVal['Wage']))
fileVal['Release Clause']=list(map(amount, fileVal['Release Clause']))

In [27]:
def hits (x):
    if 'K' in x:
        scalar=1000
        x=x.replace('K','')
    else:
        scalar=1
    x=pd.to_numeric(x, errors='coerce')*scalar
    return x
file['Hits']=list(map(hits, file['Hits']))
fileVal['Hits']=list(map(hits, fileVal['Hits']))

In [28]:
#Again, I'll eliminate categories with corr>85%
file = file.drop(['Wage', 'Release Clause'], axis=1)
fileVal = fileVal.drop(['Wage', 'Release Clause'], axis=1)

In [29]:
file = file.drop(['LS', 'RS', 'LF', 'CF', 'RF', 'LAM', 'RAM', 'LM', 'LCM', 'RCM', 'RM', 'LWB', 'LDM', 'RDM', 'RWB', 'LCB', 'RCB'], axis=1)
fileVal = fileVal.drop(['LS', 'RS', 'LF', 'CF', 'RF', 'LAM', 'RAM', 'LM', 'LCM', 'RCM', 'RM', 'LWB', 'LDM', 'RDM', 'RWB', 'LCB', 'RCB'], axis=1)

In [30]:
def progression (x):
    f,i=x.split("+")
    x=int(i)
    return x
file['GK']=list(map(progression, file['GK']))
file['CB']=list(map(progression, file['CB']))
file['LB']=list(map(progression, file['LB']))
file['RB']=list(map(progression, file['RB']))
file['CM']=list(map(progression, file['CM']))
file['CAM']=list(map(progression, file['CAM']))
file['CDM']=list(map(progression, file['CDM']))
file['ST']=list(map(progression, file['ST']))
file['RW']=list(map(progression, file['RW']))
file['LW']=list(map(progression, file['LW']))

In [31]:
fileVal['GK']=list(map(progression, fileVal['GK']))
fileVal['CB']=list(map(progression, fileVal['CB']))
fileVal['LB']=list(map(progression, fileVal['LB']))
fileVal['RB']=list(map(progression, fileVal['RB']))
fileVal['CM']=list(map(progression, fileVal['CM']))
fileVal['CAM']=list(map(progression, fileVal['CAM']))
fileVal['CDM']=list(map(progression, fileVal['CDM']))
fileVal['ST']=list(map(progression, fileVal['ST']))
fileVal['RW']=list(map(progression, fileVal['RW']))
fileVal['LW']=list(map(progression, fileVal['LW']))

In [32]:
#One hot encoding

In [33]:
from sklearn.preprocessing import OneHotEncoder

y_train = file['OVA']
X = file.drop(['OVA'], axis=1)
X_num = X.select_dtypes(include = np.number)
X_cat = X.select_dtypes(include = object)

In [34]:
encoder = OneHotEncoder(drop='first').fit(X_cat)
cols = encoder.get_feature_names(input_features=X_cat.columns)
X_cat_encode = pd.DataFrame(encoder.transform(X_cat).toarray(),columns=cols)
X_cat_encode.head()

,BP_CB,BP_CDM,BP_CF,BP_CM,BP_GK,BP_LB,BP_LM,BP_LW,BP_LWB,BP_RB,BP_RM,BP_RW,BP_RWB,BP_ST,foot_Right,A/W_Low,A/W_Medium,D/W_Low,D/W_Medium
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0

In [35]:
X_train = pd.concat([X_num, X_cat_encode], axis=1)

In [36]:
y_test = fileVal['OVA']
X = fileVal.drop(['OVA'], axis=1)
X_num = X.select_dtypes(include = np.number)
X_cat = X.select_dtypes(include = object)

In [37]:
cols = encoder.get_feature_names(input_features=X_cat.columns)
X_cat_encode = pd.DataFrame(encoder.transform(X_cat).toarray(),columns=cols)

In [38]:
X_test = pd.concat([X_num, X_cat_encode], axis=1)

In [39]:
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)

In [40]:
from sklearn import linear_model
lm = linear_model.LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [41]:
#Now I'll calculate R2 score, MSE, RMSE and MAE
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
train_pred = lm.predict(X_train)
test_pred = lm.predict(X_test)
r2t = r2_score(y_train, train_pred)
print("R2 for train:", r2t)
r2s = r2_score(y_test, test_pred)
print("\nR2 for score:", r2s)
train_mse = mean_squared_error(train_pred, y_train)
print ('\nTrain MSE: {}'.format(train_mse))
test_mse = mean_squared_error(test_pred, y_test)
print ('\nTest MSE: {}'.format(test_mse))
train_rmse = math.sqrt(train_mse)
print("\nTrain RMSE:", train_rmse)
test_rmse = math.sqrt(test_mse)
print("\nTest RMSE:", test_rmse)
train_mae = mean_absolute_error(y_train, train_pred)
print("\nTrain MAE:", train_mae)
test_mae = mean_absolute_error(y_test, test_pred)
print("\nTest MAE:", test_mae)

R2 for train: 0.9158402350097816

R2 for score: 0.9120520683308362

Train MSE: 3.978775061287654

Test MSE: 4.024627607644616

Train RMSE: 1.994686707552756

Test RMSE: 2.006147454113136

Train MAE: 1.5396434268499537

Test MAE: 1.5603349234193786